spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #配置数据源
  datasource:
    url: jdbc:mysql://192.168.31.250:3306/LostAndFound?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #配置redis
  redis:
    host: 192.168.31.250
  #  #配置mail信息
  mail:
    host: smtp.163.com
    username: kamisora2020@163.com
    password:
    port: 465
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
#配置mybatis-plus信息
mybatis-plus:
  #  global-config:
  #    db-config:
  #       id生成策略 auto为数据库自增
  #     id-type: auto
  mapper-locations: classpath*:/mapper/**/*.xml
#服务器端口
server:
  port: 8081
### fdfs配置
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 150
    height: 150
  tracker-list:
    # 可写多个tracker-server地址
    - :22122

